export const svgList100 = [
  "account-balance  1",
  "account-balance_wallet  2",
  "account-circle_off",
  "add  1",
  "add-ad",
  "add-card",
  "add-circle  1",
  "add-link",
  "admin-panel_settings",
  "alternate-email  1",
  "apps  1",
  "archive",
  "arrow-back",
  "arrow-downward",
  "arrow-drop_down  1",
  "arrow-drop_up",
  "arrow-forward",
  "arrow-left",
  "arrow-right",
  "arrow-upward",
  "assignment-ind  1",
  "attach-file_add",
  "attach-money",
  "attachment",
  "autorenew  1",
  "block  1",
  "bookmark  1",
  "border-color  1",
  "calendar-month  1",
  "call  1",
  "campaign  1",
  "cancel  1",
  "chat  1",
  "check-circle  1",
  "chevron-left  1",
  "chevron-right  1",
  "close  1",
  "content-copy  1",
  "contract  1",
  "contract-delete  1",
  "control_point",
  "corporate_fare",
  "credit-card",
  "currency-exchange",
  "cutlery",
  "dataset",
  "date-range  1",
  "delete",
  "description",
  "dns",
  "done  1",
  "done",
  "download",
  "drive-file_move",
  "edit-square  1",
  "edit",
  "error  2",
  "event-upcoming",
  "expand-less  2",
  "expand-more  2",
  "familiar-face_and_zone  1",
  "file-copy  1",
  "file-open  1",
  "filter",
  "flash-on",
  "front-hand",
  "google-wifi",
  "grid-view  1",
  "group  3",
  "group-add  2",
  "group-add  7",
  "groups  2",
  "handshake",
  "handyman",
  "help  3",
  "history  2",
  "home",
  "hourglass-empty  1",
  "iframe  1",
  "image  1",
  "info  (1) 1",
  "input",
  "inventory",
  "jamboard-kiosk",
  "key  2",
  "language-2",
  "language",
  "linked-services",
  "list",
  "location-away",
  "lock  1",
  "logout",
  "mail  1",
  "menu  1",
  "mintmark  1",
  "minus",
  "monitoring",
  "more-horiz  1",
  "more-vert",
  "motion-photos_auto  1",
  "new-label  1",
  "new-windows",
  "not-started",
  "notifications  1",
  "notifications-active  1",
  "notifications-off  1",
  "paid",
  "payments  2",
  "person  2",
  "person-kyc",
  "play-circle",
  "price-change",
  "price-check  1",
  "progress-activity",
  "qr-code_scanner  1",
  "request-quote",
  "reviews  2",
  "schedule  1",
  "search  1",
  "send  1",
  "sentiment-sadness",
  "sentiment-satisfied  (1) 1",
  "settings",
  "shadow-add  1",
  "shopping-cart  1",
  "signal-cellular-1-bar",
  "signal-cellular-3-bar",
  "signal-cellular-4-bar",
  "signal-cellular_alt",
  "signal-wifi_statusbar_not_connected",
  "smartphone",
  "smb-share",
  "sort",
  "splitscreen-add-1",
  "splitscreen-add",
  "splitscreen-succes",
  "star  1",
  "support-agent  2",
  "sync-alt  2",
  "thumbs-up_down  1",
  "timeline",
  "tune  1",
  "unarchive",
  "verified-user  1",
  "verified",
  "visibility  1",
  "visibility-off  1",
  "warning  1",
  "wifi-proxy"
] as const;
export const svgListflags = [
  "ar",
  "be",
  "bg",
  "bn",
  "cs",
  "da",
  "de",
  "el",
  "en",
  "es",
  "et",
  "fi",
  "fr",
  "hi",
  "hu",
  "id",
  "it",
  "ja",
  "ko",
  "lt",
  "lv",
  "nb",
  "nl",
  "pl",
  "pt",
  "ro",
  "ru",
  "sk",
  "sl",
  "sv",
  "sw",
  "tr",
  "uk",
  "vi",
  "zh"
] as const;
export const svgList400 = [
  "account-balance-wallet",
  "account-balance",
  "account-circle-off",
  "add-ad",
  "add-card",
  "add-circle",
  "add-link",
  "add",
  "admin-panel-settings",
  "alternate-email",
  "apps",
  "archive",
  "arrow-back",
  "arrow-downward 1",
  "arrow-drop-down 1",
  "arrow-drop-up",
  "arrow-forward 1",
  "arrow-left",
  "arrow-right",
  "arrow-upward",
  "assignment-ind",
  "attach-file-add",
  "attach-money",
  "attachment",
  "autorenew 1",
  "block",
  "bookmark",
  "border-color",
  "calendar-month",
  "call",
  "campaign",
  "cancel",
  "chat",
  "check-circle",
  "chevron-left 1",
  "chevron-right",
  "close",
  "content-copy",
  "contract-delete",
  "contract",
  "control_point",
  "corporate-fare",
  "credit-card",
  "currency-exchange",
  "cutlery",
  "dataset",
  "date-range",
  "delete",
  "description (1)",
  "dns",
  "done 1",
  "done",
  "download",
  "drive-file-move",
  "edit-square",
  "edit",
  "error",
  "event-upcoming",
  "familiar-face-and-zone",
  "file-copy",
  "file-open",
  "filter",
  "flash-on",
  "front-hand",
  "google-wifi",
  "grid-view",
  "group-add 1",
  "group",
  "groups",
  "handshake",
  "handyman",
  "help",
  "history",
  "home",
  "hourglass-empty",
  "iframe",
  "image",
  "info",
  "input",
  "inventory-2",
  "jamboard-kiosk",
  "key",
  "keyboard-arrow-down",
  "keyboard-arrow-up",
  "language-2",
  "language",
  "linked-services",
  "list",
  "location_away",
  "lock",
  "logout",
  "mail",
  "menu",
  "mintmark",
  "minus",
  "monitoring",
  "more-horiz",
  "more-vert",
  "motion-photos-auto",
  "new-label",
  "new-windows",
  "not-started",
  "notifications-active",
  "notifications-off",
  "notifications",
  "paid",
  "payments",
  "person",
  "play-circle",
  "price-change",
  "price-check",
  "progress-activity",
  "qr-code-scanner",
  "request-quote",
  "reviews",
  "schedule 1",
  "search",
  "send",
  "sentiment-satisfied",
  "settings",
  "shadow-add",
  "shopping-cart",
  "signal-cellular-1-bar",
  "signal-cellular-3-bar",
  "signal-cellular-4-bar",
  "signal-cellular-alt",
  "signal-wifi-statusbar-not_connected",
  "smartphone",
  "smb-share",
  "sort",
  "splitscreen-add",
  "splitscreen-close",
  "splitscreen-succes",
  "star",
  "support-agent",
  "sync-alt",
  "thumbs-up-down",
  "timeline",
  "tune",
  "unarchive",
  "verified-user",
  "verified",
  "visibility-off",
  "visibility",
  "warning",
  "wifi-proxy"
] as const;
export const svgListsocial = [
  "appgallery",
  "bugdroid",
  "Google play",
  "instagram",
  "logo_facebook",
  "logo_google",
  "mail",
  "Pinterest",
  "Spotify",
  "telegram-2",
  "telegram",
  "tiktok",
  "Twitch",
  "twitter",
  "Vkontakte",
  "WeChat",
  "Whatsapp",
  "windows",
  "WireGuard",
  "Yandex",
  "youtube"
] as const;
export const svgListfilled = [
  "account-balance-wallet",
  "account-balance",
  "account-circle-off",
  "add-ad",
  "add-card",
  "add-circle",
  "add-link",
  "add",
  "admin-panel-settings",
  "alternate-email",
  "apps",
  "archive",
  "arrow-back",
  "arrow-downward",
  "arrow-drop-down",
  "arrow-drop-up",
  "arrow-forward",
  "arrow-left",
  "arrow-right",
  "arrow-upward",
  "assignment-ind",
  "attach-file-add",
  "attach-money",
  "attachment",
  "autorenew",
  "block",
  "bookmark",
  "border-color",
  "calendar-month",
  "call",
  "campaign",
  "cancel",
  "chat",
  "check-circle",
  "chevron-left",
  "chevron-right",
  "close",
  "content-copy",
  "contract-delete",
  "contract",
  "control_point",
  "corporate-fare",
  "credit-card",
  "currency-exchange",
  "cutlery",
  "dataset",
  "date-range",
  "delete",
  "description",
  "dns",
  "done 1",
  "done",
  "download",
  "drive-file-move",
  "edit-square",
  "edit",
  "error",
  "event-upcoming",
  "familiar-face-and-zone",
  "file-copy",
  "file-open",
  "filter",
  "flash-on",
  "front-hand",
  "google-wifi",
  "grid-view",
  "group-add",
  "group",
  "groups",
  "handshake",
  "handyman",
  "help",
  "history",
  "home",
  "hourglass-empty",
  "iframe",
  "image",
  "info",
  "input",
  "inventory",
  "jamboard-kiosk",
  "key",
  "keyboard-arrow-down",
  "keyboard-arrow-up",
  "language-2",
  "language",
  "linked-services",
  "list",
  "location",
  "lock",
  "logout",
  "mail",
  "menu",
  "mintmark",
  "minus",
  "monitoring",
  "more-horiz",
  "more-vert",
  "motion-photos-auto",
  "new-label",
  "new-windows",
  "not-started",
  "notifications-active",
  "notifications-off",
  "notifications",
  "paid",
  "payments",
  "person",
  "play-circle",
  "price-change",
  "price-check",
  "progress-activity",
  "qr-code-scanner",
  "request-quote",
  "reviews",
  "schedule",
  "search",
  "send",
  "sentiment-satisfied",
  "settings",
  "shadow-add",
  "shopping-cart",
  "signal-cellular--bar",
  "signal-cellular-3-bar",
  "signal-cellular-4-bar",
  "signal-cellular-alt",
  "signal-wifi-statusbar-not-connected",
  "smartphone",
  "smb-share",
  "sort",
  "splitscreen-add",
  "splitscreen-close",
  "splitscreen-succes",
  "star",
  "support-agent",
  "sync-alt",
  "thumbs-up-down",
  "timeline",
  "tune",
  "unarchive",
  "verified-user",
  "verified",
  "visibility-off",
  "visibility",
  "warning",
  "wifi-proxy"
] as const;
